modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "LGPL-3.0-or-later"

[[mods]]
modId = "character_sheet"
version = "${version}"
displayName = "Character Sheet Mod"
authors = "Diamssword"
description = '''
A mod modyfing most of the aspect of a player for a more roleplay experience.
'''
logoFile = "assets/character_sheet/icon.png"

[[dependencies.character_sheet]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.character_sheet]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.character_sheet]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
